---
kind: pipeline
type: docker
name: Build (amd64)
platform:
  arch: amd64

steps:
  - name: Get Dependencies
    image: node
    commands:
      - curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - pnpm i

  - name: Lint
    image: node
    depends_on:
      - Get Dependencies
    commands:
      - npm run lint:ci

  - name: Build
    image: node
    depends_on:
      - Lint
    commands:
      - npm run build

  - name: Package
    image: node
    depends_on:
      - Build
    commands:
      - npm run package -t node16-linux-x64,node16-alpine-x64,node16-macos-x64,node16-win-x64 -o dist/bin/imagebot-x64
    when:
      event:
        - tag

  - name: Make Gitea Release
    image: plugins/gitea-release
    depends_on:
      - Package
    settings:
      api_key:
        from_secret: release_api_key
      base_url: https://git.froth.zone
      files:
        - dist/bin/*
    when:
      event:
        - tag
---
kind: pipeline
type: docker
name: Build (arm64)
platform:
  arch: arm64

steps:
  - name: Get Dependencies
    image: node
    commands:
      - curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - pnpm i

  - name: Lint
    image: node
    depends_on:
      - Get Dependencies
    commands:
      - npm run lint:ci

  - name: Build
    image: node
    depends_on:
      - Lint
    commands:
      - npm run build

  - name: Package
    image: node
    depends_on:
      - Build
    commands:
      - wget "https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus2/ldid_linux_aarch64" -O /usr/local/bin/ldid && chmod +x /usr/local/bin/ldid
      - npm run package -t node16-linux-arm64,node16-alpine-arm64,node16-macos-arm64,node16-win-arm64 -o dist/bin/imagebot-arm64
    when:
      event:
        - tag

  - name: Make Gitea Release
    image: plugins/gitea-release
    depends_on:
      - Package
    settings:
      api_key:
        from_secret: release_api_key
      base_url: https://git.froth.zone
      files:
        - dist/bin/*
    when:
      event:
        - tag
