kind: pipeline
type: docker
name: default

steps:

- name: lint
  image: node
  commands:
  - yarn
  - yarn lint

- name: build
  image: node
  commands:
  - yarn build

- name: test
  image: node
  commands: 
   - yarn test
